apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-fbc-component1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-fbc-component1
    app.kubernetes.io/part-of: e2e-fbc-application1
  name: e2e-fbc-component1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: e2e-fbc-component1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: e2e-fbc-component1
    spec:
      containers:
      - image: quay.io/qijing/dev-release-team-tenant/e2e-fbc-application1/e2e-fbc-component1@sha256:5224f0e852fc19b8c85fcaae86165d4002b85f90b72aec7d8ff1bc1699ca9c0a
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
