apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: e2e-fbc-component1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/dev-release-team-tenant/e2e-fbc-application1/e2e-fbc-component1@sha256:3b771b9515d706a7208eacc8af0ee4c091e44adc8b9185af692f7c2859fdabec
        name: fbc
        resources: {}
status: {}
